### ISSUE TITLE
a mixin fails to apply in 1.14.4

### ISSUE THREAD

**Issue by Nathan22211** [CottonMC/VMulti#1]
**Describe the bug**
a crash occur upon trying to load minecraft 1.14.4 with the mod installed
**To Reproduce**
1. load minecraft 1.14.4 with the log open, vmmulti, fabric API, and cotton and check the log for a fatal error

**Expected behavior** *Optional*
the mixin should apply

**Screenshots** *Optional*

**Version of the (please complete the following information):**
 - Mod vmulti 1.0.0
 - Dependency A cotton 1.0.0 rc.3
 - Dependency B
 - Fabric API 0.3.3 build.234-1.14
 - Minecraft 1.14.4

**Additional context** *Optional*
fatal log
`Mixin apply failed mixins.vmulti.json:MixinBeaconContainerSlotPayment -> net.minecraft.class_1704$class_1705: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @Inject annotation on handler$taggableInsertSlot$zob000 could not find any targets matching 'canInsert' in the target class net.minecraft.class_1704$class_1705. Using refmap VMulti-refmap.json
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @Inject annotation on handler$taggableInsertSlot$zob000 could not find any targets matching 'canInsert' in the target class net.minecraft.class_1704$class_1705. Using refmap VMulti-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findMethods(InjectionInfo.java:421)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:172)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:159)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:151)
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:44)
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:472)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1180)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:930)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:318)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:281)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.loadClassData(KnotClassDelegate.java:180)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:143)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:962)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:987)
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1390)
	at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1746)
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477)
	at net.minecraft.class_3917.<clinit>(class_3917.java:20)
	at net.minecraft.class_2378.method_17583(class_2378.java:100)
	at net.minecraft.class_2378$$Lambda$124/1513743700.get(Unknown Source)
	at net.minecraft.class_2378.method_10238(class_2378.java:117)
	at net.minecraft.class_2378$$Lambda$135/1610818058.accept(Unknown Source)
	at java.util.LinkedHashMap$LinkedEntrySet.forEach(LinkedHashMap.java:663)
	at net.minecraft.class_2378.<clinit>(class_2378.java:116)
	at net.minecraft.class_2966.method_12851(class_2966.java:38)
	at net.minecraft.class_310.<init>(class_310.java:383)
	at net.minecraft.client.main.Main.main(Main.java:155)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:178)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:131)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
09:46:53.279
Process crashed with exit code 1`

**Comment by LemmaEOF** [comment]
Huh, that's weird. Haven't run into a mixin refmap issue like this in a little while. Lemme take a look.

**Comment by LemmaEOF** [comment]
Yeah, it looks like the VMulti refmap didn't get this method added. No idea why.

**Comment by LemmaEOF** [comment]
This is fixed in version 1.0.1! It's up on GitHub and going onto CurseForge now!
